name: Sync to GitLab

on:
  push:
    branches:
      - "**"
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
          GITLAB_REPO_URL: "https://gitlab.com/mmuratardag-websites/portfolio_website.git"
        run: |
          git push --force --all "${GITLAB_REPO_URL/https:\/\//https:\/\/oauth2:$GITLAB_ACCESS_TOKEN@}"
          git push --force --tags "${GITLAB_REPO_URL/https:\/\//https:\/\/oauth2:$GITLAB_ACCESS_TOKEN@}"